export const UPDATE_PRODUCTS = "UPDATE_PRODUCTS";

export const INCREMENT_PRODUCT = "INCREMENT_PRODUCT";
export const DECREMENT_PRODUCT = "INCREMENT_PRODUCT";
export const DELETE_PRODUCT = "DELETE_PRODUCT";
export const SHOW_ADD_PRODCUT = "SHOW_ADD_PRODCUT";
export const APPEND_PRODUCT = "APPEND_PRODUCT";
export const HIDE_ADD_PRODUCT = "HIDE_ADD_PRODUCT";
export const ADD_TO_CART = "ADD_TO_CART";
export const REMOVE_FROM_CART = "REMOVE_FROM_CART";
export const SHOW_CART_ITEMS = "SHOW_CART_ITEMS";
export const HIDE_CART_ITEMS = "HIDE_CART_ITEMS";
export const EDIT_CHANGE_INLINE = "EDIT_CHANGE_INLINE";
export const REMOVE_FROM_EDITABLE = "REMOVE_FROM_EDITABLE";
export const ADD_TO_EDITABLE = "ADD_TO_EDITABLE";
